jQuery(document).ready(function($) {
    // Preset selection handler
    $('#easy_php_settings_preset').on('change', function() {
        var presetKey = $(this).val();
        if (presetKey && window.easy_php_settingsAdminVars && window.easy_php_settingsAdminVars.presets) {
            var preset = window.easy_php_settingsAdminVars.presets[presetKey];
            if (preset) {
                var fieldsPopulated = 0;
                // Populate all settings fields with preset values
                $.each(preset, function(key, value) {
                    if (key !== 'name' && key !== 'description') {
                        if (key === 'custom_php_ini') {
                            // Handle custom php.ini textarea
                            var textarea = $('#easy_php_settings_custom_php_ini');
                            if (textarea.length) {
                                textarea.val(value);
                                fieldsPopulated++;
                            }
                        } else {
                            // Handle regular input fields
                            var input = $('input[name="easy_php_settings_settings[' + key + ']"]');
                            if (input.length) {
                                input.val(value);
                                fieldsPopulated++;
                            } else {
                                console.log('Field not found: easy_php_settings_settings[' + key + ']');
                            }
                        }
                    }
                });
                
                if (fieldsPopulated > 0) {
                    // Show professional notification
                    var message = '<div class="notice notice-success is-dismissible" style="margin: 15px 0; padding: 12px;">' +
                        '<p><strong>✓ Preset Applied Successfully!</strong></p>' +
                        '<p>The <strong>' + preset.name + '</strong> configuration has been applied. ' +
                        '<span class="status-badge ok">' + fieldsPopulated + ' Settings Updated</span></p>' +
                        '<p style="margin-top: 10px;"><em>Click "Save All Settings" below to apply these changes.</em></p>' +
                        '</div>';
                    $('.easy-php-settings-preset-box').after(message);
                    
                    // Scroll to top to show the message
                    $('html, body').animate({ scrollTop: 0 }, 300);
                    
                    // Auto-dismiss after 8 seconds
                    setTimeout(function() {
                        $('.notice-success').fadeOut(500, function() {
                            $(this).remove();
                        });
                    }, 8000);
                } else {
                    console.error('No fields were populated');
                    console.log('Available preset data:', preset);
                    alert('Error: No settings were applied. Please check the browser console for details.');
                }
            } else {
                console.error('Preset not found for key:', presetKey);
            }
        } else {
            console.error('Preset data not available. Check easy_php_settingsAdminVars:', window.easy_php_settingsAdminVars);
        }
    });

    // Configuration Generator
    $('#generate-config').on('click', function() {
        var settings = {};
        if (window.easy_php_settingsKeys && Array.isArray(window.easy_php_settingsKeys)) {
            window.easy_php_settingsKeys.forEach(function(key) {
                var input = $('input[name="easy_php_settings_settings[' + key + ']"]');
                if (input.length && input.val()) {
                    settings[key] = input.val();
                }
            });
        }
        // Generate .user.ini content
        var userIniContent = '; PHP Settings generated by Easy PHP Settings plugin\n';
        userIniContent += '; Generated on: ' + new Date().toLocaleString() + '\n\n';
        Object.keys(settings).forEach(function(key) {
            userIniContent += key + ' = ' + settings[key] + '\n';
        });
        // Add custom php.ini config if present
        var customIni = $('#easy_php_settings_custom_php_ini');
        if (customIni.length && customIni.val().trim()) {
            userIniContent += '\n; Custom php.ini directives\n' + customIni.val().trim() + '\n';
        }
        // Generate .htaccess content
        var htaccessContent = '# PHP Settings generated by Easy PHP Settings plugin\n';
        htaccessContent += '# Generated on: ' + new Date().toLocaleString() + '\n\n';
        Object.keys(settings).forEach(function(key) {
            htaccessContent += 'php_value ' + key + ' ' + settings[key] + '\n';
        });
        // Add custom php.ini config as comments to .htaccess
        if (customIni.length && customIni.val().trim()) {
            htaccessContent += '\n# Custom php.ini directives\n';
            htaccessContent += customIni.val().trim().split('\n').map(function(line){ return '# ' + line; }).join('\n') + '\n';
        }
        $('#user-ini-content').val(userIniContent);
        $('#htaccess-content').val(htaccessContent);
        $('#config-output').show();
    });

    // Copy to clipboard (legacy / config generator)
    window.copyToClipboard = function(elementId) {
        var textarea = document.getElementById(elementId);
        if (!textarea) return;
        var text = textarea.value;
        if (typeof navigator.clipboard !== 'undefined' && navigator.clipboard.writeText) {
            navigator.clipboard.writeText(text).then(function() {
                var $btn = $(textarea).siblings('.easy-php-copy-config, button').first();
                showCopyFeedback($btn);
            });
        } else {
            textarea.select();
            document.execCommand('copy');
            alert(easy_php_settingsAdminVars.copiedText);
        }
    };

    // Config generator copy buttons
    $(document).on('click', '.easy-php-copy-config', function() {
        var btn = $(this);
        var target = btn.data('target');
        var textarea = document.getElementById(target);
        if (textarea && textarea.value) {
            if (typeof navigator.clipboard !== 'undefined' && navigator.clipboard.writeText) {
                navigator.clipboard.writeText(textarea.value).then(function() {
                    showCopyFeedback(btn);
                });
            } else {
                textarea.select();
                document.execCommand('copy');
            }
            showCopyFeedback(btn);
        }
    });

    // Copy snippet buttons (manual config)
    $(document).on('click', '.easy-php-copy-snippet', function() {
        var btn = $(this);
        var text = btn.data('text');
        if (!text) return;
        if (typeof navigator.clipboard !== 'undefined' && navigator.clipboard.writeText) {
            navigator.clipboard.writeText(text).then(function() {
                showCopyFeedback(btn);
            });
        } else {
            var $ta = $('<textarea>').val(text).appendTo('body').select();
            document.execCommand('copy');
            $ta.remove();
            showCopyFeedback(btn);
        }
    });

    function showCopyFeedback($btn) {
        if (!$btn || !$btn.length) return;
        var orig = $btn.text();
        $btn.text(easy_php_settingsAdminVars.copiedText || 'Copied!').prop('disabled', true);
        setTimeout(function() {
            $btn.text(orig).prop('disabled', false);
        }, 1500);
    }

    // Test Settings
    $('#test-settings').on('click', function() {
        var results = $('#test-results');
        results.html('<p>Testing settings...</p>');
        setTimeout(function() {
            results.html('<p style="color: green;">✓ ' + easy_php_settingsAdminVars.testCompleted + '</p>');
        }, 1000);
    });

    // PHP Settings Search and Copy functionality
    (function(){
        // Search filter
        var searchInput = document.getElementById('php-settings-search');
        var table = document.getElementById('phpinfo-table');
        if (searchInput && table) {
            searchInput.addEventListener('input', function() {
                var filter = this.value.toLowerCase();
                var rows = table.getElementsByTagName('tr');
                for (var i = 1; i < rows.length; i++) { // skip header
                    var cells = rows[i].getElementsByTagName('td');
                    var match = false;
                    for (var j = 0; j < cells.length; j++) {
                        if (cells[j].textContent.toLowerCase().indexOf(filter) > -1) {
                            match = true;
                            break;
                        }
                    }
                    rows[i].style.display = match ? '' : 'none';
                }
            });
        }
        // Copy selected
        var copyBtn = document.getElementById('php-settings-copy-selected');
        if (copyBtn && table) {
            copyBtn.addEventListener('click', function() {
                var rows = table.querySelectorAll('tbody tr');
                var output = '';
                rows.forEach(function(row) {
                    var checkbox = row.querySelector('input[type="checkbox"]');
                    if (checkbox && checkbox.checked) {
                        var key = row.querySelector('.value')?.closest('td')?.previousElementSibling?.textContent?.trim() || '';
                        var value = row.querySelector('.value')?.textContent?.trim() || '';
                        if (key && value) {
                            output += key + ' = ' + value + '\n';
                        }
                    }
                });
                if (output) {
                    var temp = document.createElement('textarea');
                    temp.value = output;
                    document.body.appendChild(temp);
                    temp.select();
                    document.execCommand('copy');
                    document.body.removeChild(temp);
                    alert(easy_php_settingsAdminVars.copiedText);
                } else {
                    alert(easy_php_settingsAdminVars.noRowsSelected || 'No rows selected.');
                }
            });
        }
    })();

    // Extensions search functionality
    var extensionsSearch = document.getElementById('extensions-search');
    if (extensionsSearch) {
        extensionsSearch.addEventListener('input', function() {
            var filter = this.value.toLowerCase();
            var extensionLists = document.querySelectorAll('.extensions-list');
            extensionLists.forEach(function(list) {
                var rows = list.getElementsByTagName('tr');
                for (var i = 0; i < rows.length; i++) {
                    var text = rows[i].textContent.toLowerCase();
                    rows[i].style.display = text.indexOf(filter) > -1 ? '' : 'none';
                }
            });
        });
    }

    // Help icons are now rendered server-side with tooltips

    // Utility function: Convert value to bytes
    function toBytes(val) {
        if (!val) return 0;
        var num = parseInt(val);
        var unit = val.slice(-1).toUpperCase();
        if (unit === 'G') return num * 1024 * 1024 * 1024;
        if (unit === 'M') return num * 1024 * 1024;
        if (unit === 'K') return num * 1024;
        return num;
    }

    // Debounce function
    function debounce(func, wait) {
        var timeout;
        return function() {
            var context = this, args = arguments;
            clearTimeout(timeout);
            timeout = setTimeout(function() {
                func.apply(context, args);
            }, wait);
        };
    }

    // Real-time validation with debouncing
    var validateField = debounce(function(field) {
        var $field = $(field);
        var fieldName = $field.attr('name');
        var value = $field.val();
        
        // Remove existing error messages
        $field.next('.field-error').remove();
        $field.removeClass('error');
        
        if (!value) return; // Skip empty fields
        
        var errors = [];
        
        // Validate format
        if (fieldName.indexOf('memory_limit') !== -1 || 
            fieldName.indexOf('upload_max_filesize') !== -1 || 
            fieldName.indexOf('post_max_size') !== -1) {
            if (!/^\d+[KMGT]?$/i.test(value)) {
                errors.push('Invalid format. Use number followed by optional unit (K, M, G, T).');
            }
        }
        
        if (fieldName.indexOf('max_execution_time') !== -1 || 
            fieldName.indexOf('max_input_vars') !== -1) {
            if (!/^\d+$/.test(value)) {
                errors.push('Must be a number.');
            }
        }
        
        // Show errors
        if (errors.length > 0) {
            $field.addClass('error');
            var errorHtml = '<span class="field-error" style="color: #d63638; display: block; margin-top: 5px; font-size: 12px;">' + 
                errors.join('<br>') + '</span>';
            $field.after(errorHtml);
        }
    }, 500);

    // Attach real-time validation to input fields
    $('input[name^="easy_php_settings_settings"]').on('input', function() {
        validateField(this);
    });

    // Validate relationships on change
    function validateRelationships() {
        var postMaxSize = $('input[name="easy_php_settings_settings[post_max_size]"]').val();
        var uploadMaxFilesize = $('input[name="easy_php_settings_settings[upload_max_filesize]"]').val();
        var memoryLimit = $('input[name="easy_php_settings_settings[memory_limit]"]').val();
        
        // Remove existing relationship warnings
        $('.relationship-warning').remove();
        
        var warnings = [];
        
        if (postMaxSize && uploadMaxFilesize) {
            if (toBytes(postMaxSize) < toBytes(uploadMaxFilesize)) {
                warnings.push({
                    field: 'post_max_size',
                    message: 'post_max_size should be larger than upload_max_filesize.'
                });
            }
        }
        
        if (memoryLimit && postMaxSize) {
            if (toBytes(memoryLimit) < toBytes(postMaxSize)) {
                warnings.push({
                    field: 'memory_limit',
                    message: 'memory_limit should be larger than post_max_size.'
                });
            }
        }
        
        // Display warnings
        warnings.forEach(function(warning) {
            var $field = $('input[name="easy_php_settings_settings[' + warning.field + ']"]');
            if ($field.length) {
                var warningHtml = '<span class="relationship-warning" style="color: #d63638; display: block; margin-top: 5px; font-size: 12px;">' +
                    '⚠ ' + warning.message + '</span>';
                $field.closest('td, .form-field').find('.relationship-warning').remove();
                $field.closest('td, .form-field').append(warningHtml);
            }
        });
    }

    // Attach relationship validation
    $('input[name="easy_php_settings_settings[post_max_size]"], ' +
      'input[name="easy_php_settings_settings[upload_max_filesize]"], ' +
      'input[name="easy_php_settings_settings[memory_limit]"]')
        .on('input', debounce(validateRelationships, 500));

    // Client-side validation on form submit
    $('form').on('submit', function(e) {
        var form = $(this);
        
        // Only validate if it's the settings form
        if (!form.find('input[name^="easy_php_settings_settings"]').length) {
            return true;
        }

        var warnings = [];
        
        // Get values
        var postMaxSize = $('input[name="easy_php_settings_settings[post_max_size]"]').val();
        var uploadMaxFilesize = $('input[name="easy_php_settings_settings[upload_max_filesize]"]').val();
        var memoryLimit = $('input[name="easy_php_settings_settings[memory_limit]"]').val();
        var maxExecutionTime = $('input[name="easy_php_settings_settings[max_execution_time]"]').val();

        // Validation checks
        if (postMaxSize && uploadMaxFilesize) {
            if (toBytes(postMaxSize) < toBytes(uploadMaxFilesize)) {
                warnings.push('Warning: post_max_size should be larger than upload_max_filesize.');
            }
        }

        if (memoryLimit && postMaxSize) {
            if (toBytes(memoryLimit) < toBytes(postMaxSize)) {
                warnings.push('Warning: memory_limit should be larger than post_max_size.');
            }
        }

        if (maxExecutionTime && parseInt(maxExecutionTime) < 30) {
            warnings.push('Warning: max_execution_time is very low (less than 30 seconds) and may cause issues.');
        }

        if (memoryLimit && toBytes(memoryLimit) > 536870912) { // 512M
            warnings.push('Notice: memory_limit is very high (over 512M). This may be excessive unless you have a specific need.');
        }

        // Check for field errors
        if ($('.field-error').length > 0) {
            warnings.push('Please fix the validation errors before saving.');
            $('html, body').animate({
                scrollTop: $('.field-error').first().offset().top - 100
            }, 500);
            return false;
        }

        // Show warnings if any
        if (warnings.length > 0) {
            var proceed = confirm(
                'Configuration Warnings Detected!\n\n' +
                warnings.join('\n\n') +
                '\n\nThese issues may affect your site\'s performance or functionality.\n\n' +
                'Do you want to save anyway?'
            );
            
            return proceed;
        }

        return true;
    });

    // Add dismiss functionality for notices
    $(document).on('click', '.notice.is-dismissible .notice-dismiss, .notice.is-dismissible button.notice-dismiss', function(e) {
        e.preventDefault();
        $(this).closest('.notice').fadeOut(300, function() {
            $(this).remove();
        });
    });

    // Improve form submission feedback with loading states
    $('form').on('submit', function() {
        var submitButton = $(this).find('input[type="submit"], button[type="submit"]');
        if (submitButton.length && !submitButton.hasClass('no-loading')) {
            submitButton.prop('disabled', true);
            var originalText = submitButton.val() || submitButton.text();
            if (submitButton.is('button')) {
                submitButton.html('<span class="dashicons dashicons-update-alt" style="animation: rotation 1s infinite linear; display: inline-block;"></span> ' + originalText);
            } else {
                submitButton.val('Processing...');
            }
            
            // Add loading overlay
            if (!$('.easy-php-settings-loading-overlay').length) {
                $('body').append('<div class="easy-php-settings-loading-overlay" style="position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.5); z-index: 999999; display: flex; align-items: center; justify-content: center;"><div style="background: white; padding: 20px; border-radius: 4px;"><span class="dashicons dashicons-update-alt" style="animation: rotation 1s infinite linear; display: inline-block; font-size: 32px;"></span><p>Saving settings...</p></div></div>');
            }
        }
    });

    // Keyboard shortcuts
    $(document).on('keydown', function(e) {
        // Ctrl/Cmd + S to save
        if ((e.ctrlKey || e.metaKey) && e.key === 's') {
            var $form = $('form:visible').first();
            if ($form.length && $form.find('input[name^="easy_php_settings_settings"]').length) {
                e.preventDefault();
                $form.submit();
            }
        }
        
        // Escape to close modals/notices
        if (e.key === 'Escape') {
            $('.notice.is-dismissible').fadeOut(300, function() {
                $(this).remove();
            });
        }
    });

    // Debounce search inputs
    $('#php-settings-search, #extensions-search').on('input', debounce(function() {
        // Search functionality is already implemented, just debounced now
    }, 300));

    // Add success animation on save
    $(document).on('wp-settings-updated', function() {
        $('.wrap h1').after('<div class="notice notice-success is-dismissible" style="animation: slideDown 0.3s ease-out;"><p>Settings saved successfully!</p></div>');
        setTimeout(function() {
            $('.notice-success').fadeOut(500, function() {
                $(this).remove();
            });
        }, 3000);
    });

    // CSS for animations
    if (!$('#easy-php-settings-animations').length) {
        $('head').append('<style id="easy-php-settings-animations">' +
            '@keyframes rotation { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }' +
            '@keyframes slideDown { from { opacity: 0; transform: translateY(-20px); } to { opacity: 1; transform: translateY(0); } }' +
            '.error { border-color: #d63638 !important; }' +
            '</style>');
    }
}); 